# Generated by Django 3.1.2 on 2020-10-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='category',
            field=models.CharField(choices=[('friends', 'friends'), ('family', 'family')], max_length=20, null=True),
        ),
    ]
