# Generated by Django 3.1.2 on 2020-10-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_human_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
