# Generated by Django 3.1.2 on 2020-10-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201025_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='human_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
